// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type kcacheConnKey struct {
	_       structs.HostLayout
	SrcIp   uint32
	SrcPort uint16
	Pad     uint16
}

type kcacheConnVal struct {
	_           structs.HostLayout
	OrigDstIp   uint32
	OrigDstPort uint16
	Pad         uint16
}

type kcacheProxyTgt struct {
	_    structs.HostLayout
	Ip   uint32
	Port uint16
	Pad  uint16
}

// loadKcache returns the embedded CollectionSpec for kcache.
func loadKcache() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_KcacheBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load kcache: %w", err)
	}

	return spec, err
}

// loadKcacheObjects loads kcache and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*kcacheObjects
//	*kcachePrograms
//	*kcacheMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadKcacheObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadKcache()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// kcacheSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type kcacheSpecs struct {
	kcacheProgramSpecs
	kcacheMapSpecs
	kcacheVariableSpecs
}

// kcacheProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type kcacheProgramSpecs struct {
	TcEgress  *ebpf.ProgramSpec `ebpf:"tc_egress"`
	TcIngress *ebpf.ProgramSpec `ebpf:"tc_ingress"`
}

// kcacheMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type kcacheMapSpecs struct {
	OrigDst     *ebpf.MapSpec `ebpf:"orig_dst"`
	ProxyTgtMap *ebpf.MapSpec `ebpf:"proxy_tgt_map"`
}

// kcacheVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type kcacheVariableSpecs struct {
}

// kcacheObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadKcacheObjects or ebpf.CollectionSpec.LoadAndAssign.
type kcacheObjects struct {
	kcachePrograms
	kcacheMaps
	kcacheVariables
}

func (o *kcacheObjects) Close() error {
	return _KcacheClose(
		&o.kcachePrograms,
		&o.kcacheMaps,
	)
}

// kcacheMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadKcacheObjects or ebpf.CollectionSpec.LoadAndAssign.
type kcacheMaps struct {
	OrigDst     *ebpf.Map `ebpf:"orig_dst"`
	ProxyTgtMap *ebpf.Map `ebpf:"proxy_tgt_map"`
}

func (m *kcacheMaps) Close() error {
	return _KcacheClose(
		m.OrigDst,
		m.ProxyTgtMap,
	)
}

// kcacheVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadKcacheObjects or ebpf.CollectionSpec.LoadAndAssign.
type kcacheVariables struct {
}

// kcachePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadKcacheObjects or ebpf.CollectionSpec.LoadAndAssign.
type kcachePrograms struct {
	TcEgress  *ebpf.Program `ebpf:"tc_egress"`
	TcIngress *ebpf.Program `ebpf:"tc_ingress"`
}

func (p *kcachePrograms) Close() error {
	return _KcacheClose(
		p.TcEgress,
		p.TcIngress,
	)
}

func _KcacheClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed kcache_bpfel.o
var _KcacheBytes []byte
