// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type latchConnKey struct {
	_       structs.HostLayout
	SrcIp   uint32
	SrcPort uint16
	Pad     uint16
}

type latchConnVal struct {
	_           structs.HostLayout
	OrigDstIp   uint32
	OrigDstPort uint16
	Pad         uint16
}

type latchProxyTgt struct {
	_    structs.HostLayout
	Ip   uint32
	Port uint16
	Pad  uint16
}

// loadLatch returns the embedded CollectionSpec for latch.
func loadLatch() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_LatchBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load latch: %w", err)
	}

	return spec, err
}

// loadLatchObjects loads latch and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*latchObjects
//	*latchPrograms
//	*latchMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadLatchObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadLatch()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// latchSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type latchSpecs struct {
	latchProgramSpecs
	latchMapSpecs
	latchVariableSpecs
}

// latchProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type latchProgramSpecs struct {
	TcEgress  *ebpf.ProgramSpec `ebpf:"tc_egress"`
	TcIngress *ebpf.ProgramSpec `ebpf:"tc_ingress"`
}

// latchMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type latchMapSpecs struct {
	OrigDst     *ebpf.MapSpec `ebpf:"orig_dst"`
	ProxyTgtMap *ebpf.MapSpec `ebpf:"proxy_tgt_map"`
}

// latchVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type latchVariableSpecs struct {
}

// latchObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadLatchObjects or ebpf.CollectionSpec.LoadAndAssign.
type latchObjects struct {
	latchPrograms
	latchMaps
	latchVariables
}

func (o *latchObjects) Close() error {
	return _LatchClose(
		&o.latchPrograms,
		&o.latchMaps,
	)
}

// latchMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadLatchObjects or ebpf.CollectionSpec.LoadAndAssign.
type latchMaps struct {
	OrigDst     *ebpf.Map `ebpf:"orig_dst"`
	ProxyTgtMap *ebpf.Map `ebpf:"proxy_tgt_map"`
}

func (m *latchMaps) Close() error {
	return _LatchClose(
		m.OrigDst,
		m.ProxyTgtMap,
	)
}

// latchVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadLatchObjects or ebpf.CollectionSpec.LoadAndAssign.
type latchVariables struct {
}

// latchPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadLatchObjects or ebpf.CollectionSpec.LoadAndAssign.
type latchPrograms struct {
	TcEgress  *ebpf.Program `ebpf:"tc_egress"`
	TcIngress *ebpf.Program `ebpf:"tc_ingress"`
}

func (p *latchPrograms) Close() error {
	return _LatchClose(
		p.TcEgress,
		p.TcIngress,
	)
}

func _LatchClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed latch_bpfel.o
var _LatchBytes []byte
