# SPDX-FileCopyrightText: Copyright (c) 2026, the kcache developers
#
# SPDX-License-Identifier: Apache-2.0

"on":
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: codeberg-tiny-lazy
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                  go-version-file: go.mod
                  cache: true
            - run: go vet ./...
            - run: go test -race ./...

    reuse:
        runs-on: codeberg-tiny-lazy
        steps:
            - uses: actions/checkout@v4
            - uses: fsfe/reuse-action@v5
