# SPDX-FileCopyrightText: Copyright (c) 2026, the kcache developers
#
# SPDX-License-Identifier: Apache-2.0

on:
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                  go-version-file: go.mod
                  cache: true
            - run: go vet ./...
            - run: go test -race ./...

    reuse:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: fsfe/reuse-action@v5
