# SPDX-FileCopyrightText: Copyright (c) 2026, the k-cache developers
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: kcache.io/v1alpha1
kind: CachePolicy
metadata:
  name: {{ include "kcache-demo.name" . }}-default
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  rules:
    - host: "*"
      port: 80
      methods: [GET]
      ttl: 60s
