apiVersion: v1
kind: Service
metadata:
  name: {{ include "kcache-demo.fullname" . }}-backend
  labels:
    {{- include "kcache-demo.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    {{- include "kcache-demo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
